### PR TITLE
Changed Simplified Chinese file name from ch.json to zh_CN.json and added Japanese, Ryukyuan and Traditional Chinese translations

### PR DESCRIPTION
**Pull request by kuragehimekurara1**
Changed Simplified Chinese file name from ch.json to zh_CN.json and added Japanese, Ryukyuan and Traditional Chinese translations

### CODE REVIEW

**Comment by kuragehimekurara1** [comment]
If you do not understand the Ryukyuan languages, please see this Wikipedia page.
https://en.wikipedia.org/wiki/Ryukyuan_languages

**Comment by averne** [comment]
Nice, thanks for the work.
Question: I would need to know how to write the name of these languages natively, as in here: https://github.com/averne/Turnips/blob/master/src/gui.cpp#L456

**Comment by kuragehimekurara1** [comment]
I wrote Japanese, Ryukyuan languages, and traditional Chinese language names natively.

**Comment by averne** [comment]
Thanks again for your effort

**Pull request merged**
