### PR TITLE
Update es.json

### PR DESCRIPTION
**Pull request by ROYSO72**
Repair line break in seed section

### CODE REVIEW

**Comment by averne** [comment]
Why is this needed? The newline as it is (so as the line takes up the entirety of the window), is consistent with the other languages.

**Comment by ROYSO72** [comment]
It is not a new line. It is to advance the line break because where it was
placed before it caused the sentence to be cut off by the size of the
window (there were two words that were not seen).

**Comment by ROYSO72** [comment]
It is not a new line.  It is to advance the line break because where it was placed before it caused the sentence to be cut off by the size of the window (there were two words that were not seen).

**Comment by averne** [comment]
Does that happen in docked mode?

**Comment by ROYSO72** [comment]
Yes, only in docked Mode.

Ser pictures in this link

https://www.dropbox.com/s/1rcve2vmm4ketx7/IMG_20200817_135700.jpg?dl=0

https://www.dropbox.com/s/1rcve2vmm4ketx7/IMG_20200817_135700.jpg?dl=0

**Comment by ROYSO72** [comment]
Sorry, suplicante links.

This is in docked mode

https://www.dropbox.com/s/zg1sd7rchrzs56g/IMG_20200817_135737.jpg?dl=0

**Comment by averne** [comment]
Ok, good to know. I can't test in docked mode right now, so I'm gonna merge this as a temporary workaround. 
In the future, fonts should probably be scaled differently in docked mode.

**Pull request merged**
