### PR TITLE
I add a language option 

### PR DESCRIPTION
**Pull request by tiansongyu**
Hey!!! I like your app and I create a new branch for a new language option.I add some code and add the chinese language option.
I put the language translation file into the json file .If you want to add some more language .example ，Japanese, French and German.  You just need change a little code and add the language translation json file into the Path(res/lang).
I thought My Programming level sucks.:( . I just code according to my Programming habits.
And you can reference my code to add a language option .or you directly use my code .this's all fine .
anyway.I like your app.I thought it's useful。

and  Basically,I don't change your code .I just add  json\type\lang files that I need .and add some code in your gui.hpp gui.cpp.parser.hpp. and change some const data type .I have to change the type of data and function .as you know the name of week cannot be a const data because I need change the word example friday ，in chinese is 星期五.:) !!!

more inportant thing is I add a workflow file . it can build your app in the cloud server .the workflow is fine . I thought you should use it before you release the code .It's amazing and convenient.

I hope my work is good for you .You just can use the file that by the workflow producting .it's a zip file .inside thing is a nro file .you can try it and I think my app is Ok .I mean It can build pass.

have a good day :) !!!

### CODE REVIEW

**Comment by tiansongyu** [comment]
You can download the nro file from here  https://github.com/tiansongyu/Turnips/suites/944017137/artifacts/11702759
the app will Automaticity fine the systemlanguage of the user and set the right language for user.
I haven't set a file to save the language setting. I thought it's not necessary for now.
Anyone can translate for this app .just somebody supply the translation file .Then you add the option in app(need add some code about different language ).
then done.:D

**Comment by averne** [comment]
Any reason for using an external font file instead of loading the system standard/cjk fonts?

**Comment by tiansongyu** [comment]
I don't know  the system standard/cjk fonts wether have the Chinese Fonts .(and other Korean，Russian ....)
If it has ,you can use the standard/cjk fonts. I know using an external font is a bad way,It Takes up too much space. The best way is using the standard fonts.

**Comment by averne** [comment]
Okay, I'm gonna merge this but will probably refactor most of it. Thanks for the PR.

**Comment by tiansongyu** [comment]
It's my pleasure. Thank for your work!!!:)

**Comment by averne** [comment]
Hey, so I reworked it a bit, using system fonts. I also simplified the system for visitors, days etc.
I looked online for Chinese names of NPCs but a few are missing (namely Kicks and Leif). Also, some don't seem to print correctly (see below, in this case CJ on Monday and Gulliver on Friday).
Maybe those characters are from traditional Chinese?
2020072121512400-DB1426D1DFD034027CECDE9C2DD914B8

**Comment by tiansongyu** [comment]
I know That why.
The Chinese language has more than 30,000 characters.but usually  Most of the stardand system fonts only have the The commonly used charaters To save space.the number is about 2000 . For the most part,the  2000 charaters is enough to use .but Unfortunately the namely Kicks and Leif in chinese are not in the 2000 charaters . it doesn't matter with  traditional Chinese .
tranditional Chinese also have 30000 characters and 2000 commonly used charaters   :0.

The solution is replace the name of Kicks and Leif in chinese . you have my word .it's okey , the name of English have lots of meaning in Chinese . and there is not a correct absolutely translation. The English name And Chinese name are not one to one .
just replace another charaters that you can use ( in 2000charaters,it's enough to use).

I think only the chinese charaters have that problem .that why I use the  external font.So far it's great to use system standard font.because in chinese app,We usually use the 2000 charaters two  to save space .

(I strongly recommend not to translation in chinese .Chinese People don't understand the name that you translation.it's just different with the chinese name in that game .It would be worse，I think use the English name is fine in Chinese translation .or you can just use the English name in chinese translation file .Let me translate it .people just don't know who 毫不,棉儿，龙克斯  are .the name are so wire .people cannot find the corresponding name in game .if you use English name or the name I translate ,I think people will Know who they are .

Thanks a lot .I will view your code and learn to how to use system standard font .have a good day :)

**Comment by tiansongyu** [comment]
`        io.Fonts->AddFontFromMemoryTTF(chinese.address,  chinese.size,  20.0f, &font_cfg, io.Fonts->GetGlyphRangesChineseSimplifiedCommon());`
try not to use the GetGlyphRangesChineseSimplifiedCommon function .this function use 2000 charaters. I remember there is another function use the all charaters (30000). it seem that is GetGlyphRangesChineseSimplified. try it . I think it's ok.
if not ,It's because the system font charater just do not contains the   28000(30000-2000)charaters .There is no other way except use the external font ,It's best not to use it . just use  the English name In chinese translation file ,it's ok

**Comment by tiansongyu** [comment]
one question .
where do you get the switch funtion just like 
`    if (R_SUCCEEDED(plGetSharedFontByType(&standard,     PlSharedFontType_Standard)) &&
            R_SUCCEEDED(plGetSharedFontByType(&extended, PlSharedFontType_NintendoExt)) &&
            R_SUCCEEDED(plGetSharedFontByType(&chinese,  PlSharedFontType_ChineseSimplified)) &&
            R_SUCCEEDED(plGetSharedFontByType(&korean,   PlSharedFontType_KO))) {`
I don't know where to find it .do you have any way to view the document? the switch examples don't constion this function.

 I want to learn it .I don't have a document . Thank you .

**Comment by tiansongyu** [comment]
using `io.Fonts->GetGlyphRangesChineseFull()` can loading the the missing charaters .but bad news is it takes too long time to loading. If using `io.Fonts->GetGlyphRangesChineseFull()` ,the app need about more 2 second to open. you can try that 
I thought just using the `io.Fonts->GetGlyphRangesChineseSimplifiedCommon()` and  change the name of NPC

**Comment by averne** [comment]
Ok thanks, I reverted those NPC names to the English counterparts.

**Comment by averne** [comment]
Yeah, I noticed the app is slower to start up because of it needs to build the font atlas with Chinese/Korean characters. 
About those switch functions, they are provided by libnx [here](https://github.com/switchbrew/libnx/blob/master/nx/include/switch/services/pl.h#L18-L24). They aren't included in [this example](https://github.com/switchbrew/switch-examples/blob/master/graphics/shared_font/source/main.c), but if you wanted, you could PR some CJK example/add it to the existing one.

**Comment by tiansongyu** [comment]
Thanks a lot :)

**Pull request merged**
