### PR TITLE
Add speech-bubble background

### PR DESCRIPTION
**Pull request by duckyb**
I made a new asset for the background image.
here is a preview of what it will look like:

bubble-preview

I think it would be really cool if you could make it look more like a native speech bubble of the game.
For example by changing the table background color to the color of the bubble (100% transparency or `#fff9e3`)

### CODE REVIEW

**Comment by averne** [comment]
Thanks for the PR. I changed the colortheme to light to fit the background better. It might be worth tweaking the style (see https://github.com/ocornut/imgui/blob/5ac5d3674fc79bfb41634df6ce412eb9bc098453/imgui_draw.cpp#L289) but I don't really have the time for this right now.

**Comment by neonsea** [comment]
What about letting users define their own styles via a config file?

**Comment by duckyb** [comment]
@averne I could try to make a theme but I don't really understand what kind of color-encoding that is.
Are you able to use hex or rgb color encodings?

**Comment by duckyb** [comment]
> What about letting users define their own styles via a config file?

That's a bit overkill imo

**Comment by averne** [comment]
> @averne I could try to make a theme but I don't really understand what kind of color-encoding that is.
> Are you able to use hex or rgb color encodings?
> 
> PS. I think you forgot to release this version

Colors are made of 4 floats (R, B, G, A). For instance the following snippet makes the window background some kind of beige: 
```cpp
    auto *colors = style.Colors;
    colors[ImGuiCol_WindowBg] = ImVec4(0.8f, 0.6f, 0.0f, 0.5f);
```
(put it [here](https://github.com/averne/Turnips/blob/master/src/imgui.hpp#L69)).
A lot of colors are available ([see here](https://github.com/ocornut/imgui/blob/master/imgui.h#L1087-L1144)) but in practice only a few should be needed to revamp this gui entirely since I'm using very few features.
I'll release once we get a nice theme. I should be able to work on it later this week if you're busy with other things.

> > What about letting users define their own styles via a config file?
> 
> That's a bit overkill imo

Yeah, we discussed this and agreed ideally we'd have two available themes and backgrounds (dark and light), and the app would choose the one that matches the console UI theme.

**Comment by duckyb** [comment]
Alright, we already have the dark icon, I'll make a dark version of the background too

**Comment by averne** [comment]
I did the groundwork for light/dark themes: c5f416d, plus tweaked the light colors.
Waiting for dark background and I'll tweak the colors, then we should be in a good place.
Light theme looks like this right now:
image

**Comment by duckyb** [comment]
[turnip-tracker-night.zip](https://github.com/averne/Turnips/files/4542205/turnip-tracker-night.zip)

Here is the dark background, I attached as zip because I don't know if github comments compress images.

turnip-tracker-night

**Pull request merged**
